[[redirects]]
from = "/alwaysrenderthis/"
to = "/.netlify/functions/alwaysrerender"
status = 200
force = true
_generated_by_eleventy_serverless = "alwaysrerender"

[[redirects]]
from = "/buildfirstrequest/"
to = "/.netlify/functions/firstrequestrender"
status = 200
force = true
_generated_by_eleventy_serverless = "firstrequestrender"
